import sys
from pathlib import Path

def main():
    project_root = Path(__file__).resolve().parent
    runs_dir = project_root / "runs" / "latest"
    
    if not runs_dir.exists():
        print(f"Error: {runs_dir} does not exist. Run experiments first.")
        sys.exit(1)
        
    tex_files = list(runs_dir.glob("tab_*.tex")) + list(runs_dir.glob("numbers_*.tex"))
    
    report_path = runs_dir / "final_report.tex"
    with open(report_path, "w") as fout:
        fout.write("% CONSOLIDATED EXPERIMENTAL RESULTS\n")
        fout.write("% Auto-generated by generate_report.py\n\n")
        
        for f in sorted(tex_files):
            fout.write(f"% ================= {f.name} =================\n")
            with open(f, "r") as fin:
                fout.write(fin.read())
            fout.write("\n\n")
            
    print(f"Report generated successfully at {report_path}")

if __name__ == "__main__":
    main()
